# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-20.04
  apt_packages:
  - cmake
  - libcairo2-dev
  - libspdlog-dev
  tools:
    python: "3.8"
  jobs:
    pre_create_environment:
      - echo "Running 'pre_create_environment' at `date`"
    pre_install:
      - echo "Running 'pre_install' at `date`"
#FIXME to speed up building, we should compile spdlog
#- cd libs/spdlog/ && mkdir build && cd build
#- cmake -DCMAKE_POSITION_INDEPENDENT_CODE=ON ..
#- cmake --build .
# BUT, on rtd, we can't use sudo
# --> maybe we can change the env (CMAKE_INSTALL_PREFIX)?
#!!  sudo cmake --install .
    post_install:
      - echo "Running 'post_install' at `date`"
    pre_build:
      - echo "Running 'pre_build' at `date`"
    post_build:
      - echo "Running 'post_build' at `date`"

# RTD should checkout all submodules
submodules:
  include: all  
  recursive: true

# Build documentation in the docs/ directory with Sphinx
sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: false

# If using Sphinx, optionally build your docs in additional formats such as PDF
# formats:
#    - pdf

# Install sphinx & viren2d before building the docs
python:
  install:
  - requirements: docs/requirements.txt
  - method: pip
    path: .

