from rtd_demo_images.color_names import demo_color_names
from rtd_demo_images.markers import demo_markers
from rtd_demo_images.positioning import demo_text_anchors, demo_multiline_text
from rtd_demo_images.primitives import demo_ellipses, demo_arrows, demo_rectangles
from rtd_demo_images.line_styles import demo_line_cap, demo_line_join
from rtd_demo_images.tracking_by_detection import demo_tracking_by_detection
from rtd_demo_images.cheat_sheets import cheat_sheet_linestyle, cheat_sheet_arrowstyle
